### ISSUE TITLE
Check Net.cpp backpropagate

### ISSUE THREAD

**Issue by drozdvadym** [OpenANN/OpenANN#170]
Is there bug in checking  <code> l != 2 </code>, maybe should be <code> l != L - 1 </code> ?
```
void Net::backpropagate()
{
  Eigen::MatrixXd* e = &tempError;
  int l = L;
  for(std::vector<Layer*>::reverse_iterator layer = layers.rbegin();
      layer != layers.rend(); ++layer, --l)
    (**layer).backpropagate(e, e, l != 2);
}
```

**Comment by AlexanderFabisch** [comment]
Hi @drozdvadym,

this boolean flag indicates whether we compute the derivative dE / dX for this layer (see https://github.com/OpenANN/OpenANN/blob/master/src/FullyConnected.cpp#L101). This is not required in the first layer because there is no previous layer that would require these derivatives. Because there are L layers and the first one does not contain any weights (input layer) we can either go from 0 to L-1 and use the test l != L-2 (or l < L - 2) or we can go from L to 1 and test l != 2 (or l  > 2).

**Comment by AlexanderFabisch** [comment]
This should be more clear in the code now: 21216e3af0ed8165f752cb6c797a5985f8b10633

**Comment by drozdvadym** [comment]
Ok, i understand now. Thank you.
